import { SearchData, SearchResult } from './searchResult';

export const mockSearchResult: SearchResult = {
  query: 'avengers',
  result: {
    movie_count: 28,
    limit: 20,
    page_number: 1,
    movies: [
      {
        id: 56962,
        url: 'https://yts.mx/movies/lego-marvel-avengers-code-red-2023',
        imdb_code: 'tt28477867',
        title: 'Lego Marvel Avengers: Code Red',
        title_english: 'Lego Marvel Avengers: Code Red',
        title_long: 'Lego Marvel Avengers: Code Red (2023)',
        slug: 'lego-marvel-avengers-code-red-2023',
        year: 2023,
        rating: 5.4,
        runtime: 0,
        genres: [
          'Action',
          'Adventure',
          'Animation',
          'Comedy',
          'Family',
          'Sci-Fi',
        ],
        summary: '',
        description_full: '',
        synopsis: '',
        yt_trailer_code: 'nsTMauyViHI',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/lego_marvel_avengers_code_red_2023/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/lego_marvel_avengers_code_red_2023/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/lego_marvel_avengers_code_red_2023/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/lego_marvel_avengers_code_red_2023/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/lego_marvel_avengers_code_red_2023/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/311C80066D3060C609235DF87E6AAC85DE8AC386',
            hash: '311C80066D3060C609235DF87E6AAC85DE8AC386',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 100,
            peers: 6,
            size: '400.77 MB',
            size_bytes: 420237804,
            date_uploaded: '2023-10-27 14:00:40',
            date_uploaded_unix: 1698408040,
          },
          {
            url: 'https://yts.mx/torrent/download/BCFE622864D0980D22AABCC9580995551D85D0E9',
            hash: 'BCFE622864D0980D22AABCC9580995551D85D0E9',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '5.1',
            seeds: 100,
            peers: 11,
            size: '822.73 MB',
            size_bytes: 862694932,
            date_uploaded: '2023-10-27 14:32:36',
            date_uploaded_unix: 1698409956,
          },
          {
            url: 'https://yts.mx/torrent/download/95F911C7EC91D0FDDFDCC5BADFC7C3ED5D8A2F21',
            hash: '95F911C7EC91D0FDDFDCC5BADFC7C3ED5D8A2F21',
            quality: '2160p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x265',
            bit_depth: '10',
            audio_channels: '5.1',
            seeds: 77,
            peers: 12,
            size: '1.94 GB',
            size_bytes: 2083059139,
            date_uploaded: '2023-10-31 11:20:33',
            date_uploaded_unix: 1698747633,
          },
        ],
        date_uploaded: '2023-10-27 14:00:40',
        date_uploaded_unix: 1698408040,
      },
      {
        id: 53418,
        url: 'https://yts.mx/movies/avengers-of-justice-farce-wars-2018',
        imdb_code: 'tt6172666',
        title: 'Avengers of Justice: Farce Wars',
        title_english: 'Avengers of Justice: Farce Wars',
        title_long: 'Avengers of Justice: Farce Wars (2018)',
        slug: 'avengers-of-justice-farce-wars-2018',
        year: 2018,
        rating: 2.4,
        runtime: 87,
        genres: ['Action', 'Comedy', 'Family'],
        summary:
          'While trying to remain a good husband and father, Superbat and the Avengers of Justice come out of retirement to stop Dark Jokester and Lisp Luthor from freezing the planet.',
        description_full:
          'While trying to remain a good husband and father, Superbat and the Avengers of Justice come out of retirement to stop Dark Jokester and Lisp Luthor from freezing the planet.',
        synopsis:
          'While trying to remain a good husband and father, Superbat and the Avengers of Justice come out of retirement to stop Dark Jokester and Lisp Luthor from freezing the planet.',
        yt_trailer_code: 'QF_k6psoVAA',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/avengers_of_justice_farce_wars_2018/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avengers_of_justice_farce_wars_2018/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avengers_of_justice_farce_wars_2018/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avengers_of_justice_farce_wars_2018/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avengers_of_justice_farce_wars_2018/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/F7337CBF1E03BBC3649AF0CE1DD4D2BD1FA0C5EE',
            hash: 'F7337CBF1E03BBC3649AF0CE1DD4D2BD1FA0C5EE',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 3,
            peers: 5,
            size: '807.63 MB',
            size_bytes: 846861435,
            date_uploaded: '2023-07-22 13:17:42',
            date_uploaded_unix: 1690024662,
          },
          {
            url: 'https://yts.mx/torrent/download/CF953845E8D3B7DEF7F4063A7615CE66CD1E6DD0',
            hash: 'CF953845E8D3B7DEF7F4063A7615CE66CD1E6DD0',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '5.1',
            seeds: 3,
            peers: 6,
            size: '1.62 GB',
            size_bytes: 1739461755,
            date_uploaded: '2023-07-22 14:20:36',
            date_uploaded_unix: 1690028436,
          },
        ],
        date_uploaded: '2023-07-22 13:17:42',
        date_uploaded_unix: 1690024662,
      },
      {
        id: 52493,
        url: 'https://yts.mx/movies/film-companion-movie-reviews-avengers-endgame-2019',
        imdb_code: 'tt10241312',
        title: 'Film Companion: Movie Reviews Avengers Endgame',
        title_english: 'Film Companion: Movie Reviews Avengers Endgame',
        title_long: 'Film Companion: Movie Reviews Avengers Endgame (2019)',
        slug: 'film-companion-movie-reviews-avengers-endgame-2019',
        year: 2019,
        rating: 0,
        runtime: 0,
        genres: ['Action', 'Talk-Show'],
        summary: '',
        description_full: '',
        synopsis: '',
        yt_trailer_code: '',
        language: '',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/film_companion_movie_reviews_avengers_endgame_2019/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/film_companion_movie_reviews_avengers_endgame_2019/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/film_companion_movie_reviews_avengers_endgame_2019/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/film_companion_movie_reviews_avengers_endgame_2019/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/film_companion_movie_reviews_avengers_endgame_2019/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/1CB7F79F0DE4D9FCD4B02BCE1C502E6ECEEA6137',
            hash: '1CB7F79F0DE4D9FCD4B02BCE1C502E6ECEEA6137',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 4,
            size: '1.63 GB',
            size_bytes: 1750199173,
            date_uploaded: '2023-06-03 18:17:54',
            date_uploaded_unix: 1685809074,
          },
        ],
        date_uploaded: '2023-06-03 18:17:54',
        date_uploaded_unix: 1685809074,
      },
      {
        id: 44920,
        url: 'https://yts.mx/movies/ninja-avengers-1987',
        imdb_code: 'tt0199812',
        title: 'Ninja Avengers',
        title_english: 'Ninja Avengers',
        title_long: 'Ninja Avengers (1987)',
        slug: 'ninja-avengers-1987',
        year: 1987,
        rating: 5,
        runtime: 0,
        genres: ['Action'],
        summary:
          "Antonio, a traveling missionary Priest, seems innocent - until he wields his cross as a weapon during a train robbery. Ringo, a ninja rotten to the core, is released from prison. Antonio is the one who put him in jail, and Ringo's only desire now is to find and kill him. Antonio befriends a man named Dragon, unwittingly realizing his skills will soon save his life.",
        description_full:
          "Antonio, a traveling missionary Priest, seems innocent - until he wields his cross as a weapon during a train robbery. Ringo, a ninja rotten to the core, is released from prison. Antonio is the one who put him in jail, and Ringo's only desire now is to find and kill him. Antonio befriends a man named Dragon, unwittingly realizing his skills will soon save his life.",
        synopsis:
          "Antonio, a traveling missionary Priest, seems innocent - until he wields his cross as a weapon during a train robbery. Ringo, a ninja rotten to the core, is released from prison. Antonio is the one who put him in jail, and Ringo's only desire now is to find and kill him. Antonio befriends a man named Dragon, unwittingly realizing his skills will soon save his life.",
        yt_trailer_code: 'h8uZVSy0SB4',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/ninja_avengers_1987/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/ninja_avengers_1987/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/ninja_avengers_1987/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/ninja_avengers_1987/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/ninja_avengers_1987/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/80440E7E7A0C470B11953F1803619C640D22541B',
            hash: '80440E7E7A0C470B11953F1803619C640D22541B',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 0,
            size: '828.54 MB',
            size_bytes: 868787159,
            date_uploaded: '2022-09-07 15:52:47',
            date_uploaded_unix: 1662558767,
          },
          {
            url: 'https://yts.mx/torrent/download/BD27FAF058FF511CCEB602DAEF4B510188E3DA22',
            hash: 'BD27FAF058FF511CCEB602DAEF4B510188E3DA22',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 3,
            peers: 3,
            size: '1.5 GB',
            size_bytes: 1610612736,
            date_uploaded: '2022-09-07 16:59:16',
            date_uploaded_unix: 1662562756,
          },
        ],
        date_uploaded: '2022-09-07 15:52:47',
        date_uploaded_unix: 1662558767,
      },
      {
        id: 42013,
        url: 'https://yts.mx/movies/knives-of-the-avenger-1966',
        imdb_code: 'tt0059045',
        title: 'Knives of the Avenger',
        title_english: 'Knives of the Avenger',
        title_long: 'Knives of the Avenger (1966)',
        slug: 'knives-of-the-avenger-1966',
        year: 1966,
        rating: 5.7,
        runtime: 85,
        genres: ['Adventure'],
        summary:
          "Vikingland, the 9th Century. On a beach, a witch reads the future to Karan (Elisa Pichelli) and her young son, Moki (Luciano Polletin). Karan is the wife of King Arald (Giacomo Rossi-Stuart), who is thought to have been killed at sea. It is Karan's hope that her husband will return to rescue them from the clutches of the evil Aghen (Fausto Tozzi) a local warlord who wishes to marry her. The witch assures Karan that Arald will return, but she also warns Karan that Aghen is near and that he has every intention of marrying her to assume the kinghsip before killing her and Moki. Their only hope is to run away and live in seculsion until he king returns.As the witch predicts, Aghen returns. Together with his band of thugs, Aghen spreads fear throughout the village the kills anybody who apposed him, He is infuriated that Karan has fled, and goes to the old witch to find out where she is hiding. The old woman refuses to assist him, and also warns that a man is approaching whi will put an end to his reign of terror. Aghen laughts this off, and sends some his men to find Karan.Meanwhile, a rugged drifter named Helmut (Cameron Mitchell) is riding though the forest on horseback and stops at a cabin to ask for some food. The cabin is Karan's new hiding place. She sends him off, as she fears he might be connected with Aghen. But Moki recognizes the mans benevolent nature and persuades him to stay. At a nearby stream, Helmut catches some fish and as he sits down to each, he hears screaming from the cottage. Two of Aghen's men have arrived and are trying to abduct Karan and Moki, but Helmut comes to their rescue. Using his signature knifes, he kills both intruders and offers to clean up the mess they have made. Karan and Moki both feel drawn to him, and so Helmut is allowed to stay.Over the next few days, Helmut acts as a substitute father for Moki, and teaches him how to fish and throw knifes. Karan grows to be very fond of Helmut, but worries that, if her husband should return, he might take offence that a stranger has taken in on their lives. Helmut confesses that he is very interested in Karan, and encourages her to explain why she is living in exile. She reveals her true identity of being a princess, and Helmut is visibly shaken. Karan then tells of how, on her wedding day, Aghen incited the wrath of Rurik, an opposing monarch, by killing his wife and child. The king, who had hoped to make an alliance with Rurik, was enraged by this and orders Aghen to leave the village for good. Neverthless, Rurik struck back that same night by slaughtering many of the villagers, including the king, and raping Karan. With the death of the king, Arald took his place and swore vengance or Rurik. At the end of her story, Karan is overcome with emotion and flees from the room. Left alone, Helmut thinks to himself. He now realizes why Karan looks familiar to him. Helmut is actually Rurik, who is traveling incognito. Following his attack on the village, he lost the respect of his people and gave up his title for a life of wondering. The only reason why Karan does not recognize him is that she has only met him that fateful night, and he was wearing a mask. Although his identity is safe, Helmut/Rurik is wracked with guilt and wonders if he could actually be Moki's real father.The following day, Helmut discovers that Aghen has returned. Helmut goes to the village to find him, but while he waits at the local inn, he sees Moki looking in at him thought the window. He leaves to take the boy home, and tells Aghens men that he will return later that evening. They catch sight of a tattoo on his arm depicting a man holding the sun on his shoulders. When Aghen is informed about it, he becomes panic-stricken for he knows that only Rurik bears such a mark. Helmut/Rurik eventually confronts his enemy, promising to tear his heart out, but Aghen escapes unharmed.The next morning, King Arald and his men return from their long voyage at sea. It has taken them five years to get back home, leading everybody to think them dead, but now that they have arrived, Arald is anxious to settle the score with Rurik. When Arald catches Helmut/Rurik at the inn, he challenges him to a swordfight. Rurik backs down, and even when Arald starts attacking him, he refuses to fight back. The scene is interrupted by the arrival of Karan who tells them that Moki has been kidnapped by Aghen. Rurik breaks away from the fight and runs to the boy's aid, with a vengeful Arald close behind.Rurik and Arald reluctantly join forces to track Aghen to a cave near the beach. Rurik appears out of the shadows, and throws a knife at Aghen, which hits him right in the heart killing him at last. With Arald reunited with his family, and his vendetta against Aghen settled, Rurik quietly leaves and rides off into the sunset at the beach.",
        description_full:
          "Vikingland, the 9th Century. On a beach, a witch reads the future to Karan (Elisa Pichelli) and her young son, Moki (Luciano Polletin). Karan is the wife of King Arald (Giacomo Rossi-Stuart), who is thought to have been killed at sea. It is Karan's hope that her husband will return to rescue them from the clutches of the evil Aghen (Fausto Tozzi) a local warlord who wishes to marry her. The witch assures Karan that Arald will return, but she also warns Karan that Aghen is near and that he has every intention of marrying her to assume the kinghsip before killing her and Moki. Their only hope is to run away and live in seculsion until he king returns.As the witch predicts, Aghen returns. Together with his band of thugs, Aghen spreads fear throughout the village the kills anybody who apposed him, He is infuriated that Karan has fled, and goes to the old witch to find out where she is hiding. The old woman refuses to assist him, and also warns that a man is approaching whi will put an end to his reign of terror. Aghen laughts this off, and sends some his men to find Karan.Meanwhile, a rugged drifter named Helmut (Cameron Mitchell) is riding though the forest on horseback and stops at a cabin to ask for some food. The cabin is Karan's new hiding place. She sends him off, as she fears he might be connected with Aghen. But Moki recognizes the mans benevolent nature and persuades him to stay. At a nearby stream, Helmut catches some fish and as he sits down to each, he hears screaming from the cottage. Two of Aghen's men have arrived and are trying to abduct Karan and Moki, but Helmut comes to their rescue. Using his signature knifes, he kills both intruders and offers to clean up the mess they have made. Karan and Moki both feel drawn to him, and so Helmut is allowed to stay.Over the next few days, Helmut acts as a substitute father for Moki, and teaches him how to fish and throw knifes. Karan grows to be very fond of Helmut, but worries that, if her husband should return, he might take offence that a stranger has taken in on their lives. Helmut confesses that he is very interested in Karan, and encourages her to explain why she is living in exile. She reveals her true identity of being a princess, and Helmut is visibly shaken. Karan then tells of how, on her wedding day, Aghen incited the wrath of Rurik, an opposing monarch, by killing his wife and child. The king, who had hoped to make an alliance with Rurik, was enraged by this and orders Aghen to leave the village for good. Neverthless, Rurik struck back that same night by slaughtering many of the villagers, including the king, and raping Karan. With the death of the king, Arald took his place and swore vengance or Rurik. At the end of her story, Karan is overcome with emotion and flees from the room. Left alone, Helmut thinks to himself. He now realizes why Karan looks familiar to him. Helmut is actually Rurik, who is traveling incognito. Following his attack on the village, he lost the respect of his people and gave up his title for a life of wondering. The only reason why Karan does not recognize him is that she has only met him that fateful night, and he was wearing a mask. Although his identity is safe, Helmut/Rurik is wracked with guilt and wonders if he could actually be Moki's real father.The following day, Helmut discovers that Aghen has returned. Helmut goes to the village to find him, but while he waits at the local inn, he sees Moki looking in at him thought the window. He leaves to take the boy home, and tells Aghens men that he will return later that evening. They catch sight of a tattoo on his arm depicting a man holding the sun on his shoulders. When Aghen is informed about it, he becomes panic-stricken for he knows that only Rurik bears such a mark. Helmut/Rurik eventually confronts his enemy, promising to tear his heart out, but Aghen escapes unharmed.The next morning, King Arald and his men return from their long voyage at sea. It has taken them five years to get back home, leading everybody to think them dead, but now that they have arrived, Arald is anxious to settle the score with Rurik. When Arald catches Helmut/Rurik at the inn, he challenges him to a swordfight. Rurik backs down, and even when Arald starts attacking him, he refuses to fight back. The scene is interrupted by the arrival of Karan who tells them that Moki has been kidnapped by Aghen. Rurik breaks away from the fight and runs to the boy's aid, with a vengeful Arald close behind.Rurik and Arald reluctantly join forces to track Aghen to a cave near the beach. Rurik appears out of the shadows, and throws a knife at Aghen, which hits him right in the heart killing him at last. With Arald reunited with his family, and his vendetta against Aghen settled, Rurik quietly leaves and rides off into the sunset at the beach.",
        synopsis:
          "Vikingland, the 9th Century. On a beach, a witch reads the future to Karan (Elisa Pichelli) and her young son, Moki (Luciano Polletin). Karan is the wife of King Arald (Giacomo Rossi-Stuart), who is thought to have been killed at sea. It is Karan's hope that her husband will return to rescue them from the clutches of the evil Aghen (Fausto Tozzi) a local warlord who wishes to marry her. The witch assures Karan that Arald will return, but she also warns Karan that Aghen is near and that he has every intention of marrying her to assume the kinghsip before killing her and Moki. Their only hope is to run away and live in seculsion until he king returns.As the witch predicts, Aghen returns. Together with his band of thugs, Aghen spreads fear throughout the village the kills anybody who apposed him, He is infuriated that Karan has fled, and goes to the old witch to find out where she is hiding. The old woman refuses to assist him, and also warns that a man is approaching whi will put an end to his reign of terror. Aghen laughts this off, and sends some his men to find Karan.Meanwhile, a rugged drifter named Helmut (Cameron Mitchell) is riding though the forest on horseback and stops at a cabin to ask for some food. The cabin is Karan's new hiding place. She sends him off, as she fears he might be connected with Aghen. But Moki recognizes the mans benevolent nature and persuades him to stay. At a nearby stream, Helmut catches some fish and as he sits down to each, he hears screaming from the cottage. Two of Aghen's men have arrived and are trying to abduct Karan and Moki, but Helmut comes to their rescue. Using his signature knifes, he kills both intruders and offers to clean up the mess they have made. Karan and Moki both feel drawn to him, and so Helmut is allowed to stay.Over the next few days, Helmut acts as a substitute father for Moki, and teaches him how to fish and throw knifes. Karan grows to be very fond of Helmut, but worries that, if her husband should return, he might take offence that a stranger has taken in on their lives. Helmut confesses that he is very interested in Karan, and encourages her to explain why she is living in exile. She reveals her true identity of being a princess, and Helmut is visibly shaken. Karan then tells of how, on her wedding day, Aghen incited the wrath of Rurik, an opposing monarch, by killing his wife and child. The king, who had hoped to make an alliance with Rurik, was enraged by this and orders Aghen to leave the village for good. Neverthless, Rurik struck back that same night by slaughtering many of the villagers, including the king, and raping Karan. With the death of the king, Arald took his place and swore vengance or Rurik. At the end of her story, Karan is overcome with emotion and flees from the room. Left alone, Helmut thinks to himself. He now realizes why Karan looks familiar to him. Helmut is actually Rurik, who is traveling incognito. Following his attack on the village, he lost the respect of his people and gave up his title for a life of wondering. The only reason why Karan does not recognize him is that she has only met him that fateful night, and he was wearing a mask. Although his identity is safe, Helmut/Rurik is wracked with guilt and wonders if he could actually be Moki's real father.The following day, Helmut discovers that Aghen has returned. Helmut goes to the village to find him, but while he waits at the local inn, he sees Moki looking in at him thought the window. He leaves to take the boy home, and tells Aghens men that he will return later that evening. They catch sight of a tattoo on his arm depicting a man holding the sun on his shoulders. When Aghen is informed about it, he becomes panic-stricken for he knows that only Rurik bears such a mark. Helmut/Rurik eventually confronts his enemy, promising to tear his heart out, but Aghen escapes unharmed.The next morning, King Arald and his men return from their long voyage at sea. It has taken them five years to get back home, leading everybody to think them dead, but now that they have arrived, Arald is anxious to settle the score with Rurik. When Arald catches Helmut/Rurik at the inn, he challenges him to a swordfight. Rurik backs down, and even when Arald starts attacking him, he refuses to fight back. The scene is interrupted by the arrival of Karan who tells them that Moki has been kidnapped by Aghen. Rurik breaks away from the fight and runs to the boy's aid, with a vengeful Arald close behind.Rurik and Arald reluctantly join forces to track Aghen to a cave near the beach. Rurik appears out of the shadows, and throws a knife at Aghen, which hits him right in the heart killing him at last. With Arald reunited with his family, and his vendetta against Aghen settled, Rurik quietly leaves and rides off into the sunset at the beach.",
        yt_trailer_code: 'kllWd2O7wyY',
        language: 'it',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/knives_of_the_avenger_1966/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/knives_of_the_avenger_1966/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/knives_of_the_avenger_1966/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/knives_of_the_avenger_1966/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/knives_of_the_avenger_1966/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/02A600CAC4773B5309F20B487B632709A541AAB7',
            hash: '02A600CAC4773B5309F20B487B632709A541AAB7',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 5,
            size: '775.2 MB',
            size_bytes: 812856115,
            date_uploaded: '2022-05-12 00:28:00',
            date_uploaded_unix: 1652308080,
          },
          {
            url: 'https://yts.mx/torrent/download/47DFE937B64A155E1078E5E3C4A92FDE6B1A2F7A',
            hash: '47DFE937B64A155E1078E5E3C4A92FDE6B1A2F7A',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 1,
            peers: 2,
            size: '1.4 GB',
            size_bytes: 1503238554,
            date_uploaded: '2022-05-12 01:20:16',
            date_uploaded_unix: 1652311216,
          },
        ],
        date_uploaded: '2022-05-12 00:28:00',
        date_uploaded_unix: 1652308080,
      },
      {
        id: 35915,
        url: 'https://yts.mx/movies/masked-avenger-versus-ultra-villain-in-the-lair-of-the-naked-bikini-1997',
        imdb_code: 'tt0359669',
        title:
          'Masked Avenger Versus Ultra-Villain in the Lair of the Naked Bikini',
        title_english:
          'Masked Avenger Versus Ultra-Villain in the Lair of the Naked Bikini',
        title_long:
          'Masked Avenger Versus Ultra-Villain in the Lair of the Naked Bikini (1997)',
        slug: 'masked-avenger-versus-ultra-villain-in-the-lair-of-the-naked-bikini-1997',
        year: 1997,
        rating: 3.4,
        runtime: 90,
        genres: ['Action', 'Adventure', 'Comedy'],
        summary:
          "Masked Avenger is a hero to the modern world. He destroys his enemies with kung fu fighting, handsaws and guns, but with one small hang-up. At the sight of a woman, The Masked Avenger immediately begins to gratify himself, no matter what situation he is in. The evil Helmut Gunta plans to impregnante a virgin in order to have an heir, and the woman he has in mind is a nun, Sister Mary who happens to be the Masked Avenger's sister. Gunta has a plan to stop The Masked Avenger from getting in the way... organise a gang of strippers to keep him pre-occupied until Sister Mary is pregnant.—Artemis",
        description_full:
          "Masked Avenger is a hero to the modern world. He destroys his enemies with kung fu fighting, handsaws and guns, but with one small hang-up. At the sight of a woman, The Masked Avenger immediately begins to gratify himself, no matter what situation he is in. The evil Helmut Gunta plans to impregnante a virgin in order to have an heir, and the woman he has in mind is a nun, Sister Mary who happens to be the Masked Avenger's sister. Gunta has a plan to stop The Masked Avenger from getting in the way... organise a gang of strippers to keep him pre-occupied until Sister Mary is pregnant.—Artemis",
        synopsis:
          "Masked Avenger is a hero to the modern world. He destroys his enemies with kung fu fighting, handsaws and guns, but with one small hang-up. At the sight of a woman, The Masked Avenger immediately begins to gratify himself, no matter what situation he is in. The evil Helmut Gunta plans to impregnante a virgin in order to have an heir, and the woman he has in mind is a nun, Sister Mary who happens to be the Masked Avenger's sister. Gunta has a plan to stop The Masked Avenger from getting in the way... organise a gang of strippers to keep him pre-occupied until Sister Mary is pregnant.—Artemis",
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/masked_avenger_versus_ultra_villain_in_the_lair_of_the_naked_bikini_2000/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/masked_avenger_versus_ultra_villain_in_the_lair_of_the_naked_bikini_2000/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/masked_avenger_versus_ultra_villain_in_the_lair_of_the_naked_bikini_2000/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/masked_avenger_versus_ultra_villain_in_the_lair_of_the_naked_bikini_2000/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/masked_avenger_versus_ultra_villain_in_the_lair_of_the_naked_bikini_2000/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/8F2C47F5A6C510C84DF3747A8E116738E8237522',
            hash: '8F2C47F5A6C510C84DF3747A8E116738E8237522',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 3,
            peers: 2,
            size: '786.38 MB',
            size_bytes: 824579195,
            date_uploaded: '2021-09-24 13:24:59',
            date_uploaded_unix: 1632482699,
          },
          {
            url: 'https://yts.mx/torrent/download/7A8F3C422B5CA0A81FE95644E5F58494E6857301',
            hash: '7A8F3C422B5CA0A81FE95644E5F58494E6857301',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 1,
            peers: 0,
            size: '1.43 GB',
            size_bytes: 1535450808,
            date_uploaded: '2021-09-24 14:32:17',
            date_uploaded_unix: 1632486737,
          },
        ],
        date_uploaded: '2021-09-24 13:24:59',
        date_uploaded_unix: 1632482699,
      },
      {
        id: 33097,
        url: 'https://yts.mx/movies/manchurian-avenger-1984',
        imdb_code: 'tt0181668',
        title: 'Manchurian Avenger',
        title_english: 'Manchurian Avenger',
        title_long: 'Manchurian Avenger (1984)',
        slug: 'manchurian-avenger-1984',
        year: 1984,
        rating: 4.2,
        runtime: 87,
        genres: ['Action', 'Drama', 'Thriller'],
        summary:
          'Joe returns to Colorado after many years to help the man who brought him up, Kim. Joes father was killed by a gang looking to find some gold they believe he had found. Joe finds that Kim has also been murdered by them and tries to help his sister and her man to beat the gang and perhaps find the gold.—',
        description_full:
          'Joe returns to Colorado after many years to help the man who brought him up, Kim. Joes father was killed by a gang looking to find some gold they believe he had found. Joe finds that Kim has also been murdered by them and tries to help his sister and her man to beat the gang and perhaps find the gold.—',
        synopsis:
          'Joe returns to Colorado after many years to help the man who brought him up, Kim. Joes father was killed by a gang looking to find some gold they believe he had found. Joe finds that Kim has also been murdered by them and tries to help his sister and her man to beat the gang and perhaps find the gold.—',
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/manchurian_avenger_1985/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/manchurian_avenger_1985/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/manchurian_avenger_1985/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/manchurian_avenger_1985/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/manchurian_avenger_1985/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/38EAEB40BEE75FEC0F64EEA2B27EAA94F9C43FA2',
            hash: '38EAEB40BEE75FEC0F64EEA2B27EAA94F9C43FA2',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 2,
            size: '808.03 MB',
            size_bytes: 847280865,
            date_uploaded: '2021-06-20 23:01:07',
            date_uploaded_unix: 1624222867,
          },
          {
            url: 'https://yts.mx/torrent/download/2FA03CAF8525385A7C8F10C1636BED7D1F6CB456',
            hash: '2FA03CAF8525385A7C8F10C1636BED7D1F6CB456',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 3,
            size: '1.46 GB',
            size_bytes: 1567663063,
            date_uploaded: '2021-06-21 00:06:47',
            date_uploaded_unix: 1624226807,
          },
        ],
        date_uploaded: '2021-06-20 23:01:07',
        date_uploaded_unix: 1624222867,
      },
      {
        id: 32536,
        url: 'https://yts.mx/movies/crippled-avengers-1978',
        imdb_code: 'tt0077292',
        title: 'Crippled Avengers',
        title_english: 'Crippled Avengers',
        title_long: 'Crippled Avengers (1978)',
        slug: 'crippled-avengers-1978',
        year: 1978,
        rating: 7.3,
        runtime: 104,
        genres: ['Action', 'Drama'],
        summary:
          "A rich warlord who became evil and bitter because of his wife's murder and the amputation of his son's hands now bullies a town through terror and force. The warlord and his now-disabled son find pleasure and satisfaction in life by disabling anyone who gets in their way. Four of these victims--a hawker who has been blinded, a blacksmith who has been made deaf and mute, a drifter who has had both of his legs amputated, and the pupil of an elderly martial-arts teacher who has been made insane, all four of them because of the warlord and his son--band together and learn kung fu with the teacher's help in order to have their revenge on their enemies and use their disabilities to the best of their advantage against them in battle. The four men are tested time and time again and all four of them demonstrate their strengths and abilities to the utmost.—Chris Castellano",
        description_full:
          "A rich warlord who became evil and bitter because of his wife's murder and the amputation of his son's hands now bullies a town through terror and force. The warlord and his now-disabled son find pleasure and satisfaction in life by disabling anyone who gets in their way. Four of these victims--a hawker who has been blinded, a blacksmith who has been made deaf and mute, a drifter who has had both of his legs amputated, and the pupil of an elderly martial-arts teacher who has been made insane, all four of them because of the warlord and his son--band together and learn kung fu with the teacher's help in order to have their revenge on their enemies and use their disabilities to the best of their advantage against them in battle. The four men are tested time and time again and all four of them demonstrate their strengths and abilities to the utmost.—Chris Castellano",
        synopsis:
          "A rich warlord who became evil and bitter because of his wife's murder and the amputation of his son's hands now bullies a town through terror and force. The warlord and his now-disabled son find pleasure and satisfaction in life by disabling anyone who gets in their way. Four of these victims--a hawker who has been blinded, a blacksmith who has been made deaf and mute, a drifter who has had both of his legs amputated, and the pupil of an elderly martial-arts teacher who has been made insane, all four of them because of the warlord and his son--band together and learn kung fu with the teacher's help in order to have their revenge on their enemies and use their disabilities to the best of their advantage against them in battle. The four men are tested time and time again and all four of them demonstrate their strengths and abilities to the utmost.—Chris Castellano",
        yt_trailer_code: 'qJdww5ck-TI',
        language: 'zh',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/can_que_1978/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/can_que_1978/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/can_que_1978/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/can_que_1978/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/can_que_1978/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/A13AC2C280385ED38DE19FEFB8133CC316EEB508',
            hash: 'A13AC2C280385ED38DE19FEFB8133CC316EEB508',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 0,
            size: '978.51 MB',
            size_bytes: 1026042102,
            date_uploaded: '2022-08-07 14:19:48',
            date_uploaded_unix: 1659874788,
          },
          {
            url: 'https://yts.mx/torrent/download/1EC39C5B8E0702235D7DA5FA44E29B6883E5143F',
            hash: '1EC39C5B8E0702235D7DA5FA44E29B6883E5143F',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 4,
            peers: 0,
            size: '1.77 GB',
            size_bytes: 1900523028,
            date_uploaded: '2022-08-07 15:34:54',
            date_uploaded_unix: 1659879294,
          },
        ],
        date_uploaded: '2022-08-07 14:19:48',
        date_uploaded_unix: 1659874788,
      },
      {
        id: 30417,
        url: 'https://yts.mx/movies/next-avengers-heroes-of-tomorrow-2008',
        imdb_code: 'tt1259998',
        title: 'Next Avengers: Heroes of Tomorrow',
        title_english: 'Next Avengers: Heroes of Tomorrow',
        title_long: 'Next Avengers: Heroes of Tomorrow (2008)',
        slug: 'next-avengers-heroes-of-tomorrow-2008',
        year: 2008,
        rating: 6.2,
        runtime: 0,
        genres: [
          'Action',
          'Adventure',
          'Animation',
          'Family',
          'Fantasy',
          'Horror',
          'Sci-Fi',
        ],
        summary:
          "The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
        description_full:
          "The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
        synopsis:
          "The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
        yt_trailer_code: 'swn4H4sqm1A',
        language: 'en',
        mpa_rating: 'PG',
        background_image:
          'https://yts.mx/assets/images/movies/next_avengers_heroes_of_tomorrow_2008/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/next_avengers_heroes_of_tomorrow_2008/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/next_avengers_heroes_of_tomorrow_2008/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/next_avengers_heroes_of_tomorrow_2008/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/next_avengers_heroes_of_tomorrow_2008/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/54F1538E8CD771C62166FD34A7489838D1E6D9B6',
            hash: '54F1538E8CD771C62166FD34A7489838D1E6D9B6',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 4,
            peers: 2,
            size: '717.8 MB',
            size_bytes: 752667853,
            date_uploaded: '2021-04-15 11:41:19',
            date_uploaded_unix: 1618479679,
          },
          {
            url: 'https://yts.mx/torrent/download/6C55369329B6CFD2966442C5B63D8D2B9E6483DC',
            hash: '6C55369329B6CFD2966442C5B63D8D2B9E6483DC',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '5.1',
            seeds: 1,
            peers: 7,
            size: '1.44 GB',
            size_bytes: 1546188227,
            date_uploaded: '2021-04-15 12:27:00',
            date_uploaded_unix: 1618482420,
          },
        ],
        date_uploaded: '2021-04-15 11:41:19',
        date_uploaded_unix: 1618479679,
      },
      {
        id: 28617,
        url: 'https://yts.mx/movies/the-avenger-2012',
        imdb_code: 'tt2368537',
        title: 'The Avenger',
        title_english: 'The Avenger',
        title_long: 'The Avenger (2012)',
        slug: 'the-avenger-2012',
        year: 2012,
        rating: 5.1,
        runtime: 0,
        genres: ['Action', 'Crime', 'Mystery', 'Thriller'],
        summary:
          "When Gina Wright finds out that both of her parents were killed and that wealthy contractor Parker Randall is to blame, she vows to get even. Securing a job as a nanny to Parker's troubled stepson, Gina moves into Randall's house with plans to make him confess his part in the crime, but soon realizes that the ruthless Randall has very dark plans of his own.—Anonymous",
        description_full:
          "When Gina Wright finds out that both of her parents were killed and that wealthy contractor Parker Randall is to blame, she vows to get even. Securing a job as a nanny to Parker's troubled stepson, Gina moves into Randall's house with plans to make him confess his part in the crime, but soon realizes that the ruthless Randall has very dark plans of his own.—Anonymous",
        synopsis:
          "When Gina Wright finds out that both of her parents were killed and that wealthy contractor Parker Randall is to blame, she vows to get even. Securing a job as a nanny to Parker's troubled stepson, Gina moves into Randall's house with plans to make him confess his part in the crime, but soon realizes that the ruthless Randall has very dark plans of his own.—Anonymous",
        yt_trailer_code: '',
        language: 'es',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/a_nannys_revenge_2012/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/a_nannys_revenge_2012/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/a_nannys_revenge_2012/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/a_nannys_revenge_2012/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/a_nannys_revenge_2012/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/3CFEBA9AE671C6831E7292F8BABBE935947B111C',
            hash: '3CFEBA9AE671C6831E7292F8BABBE935947B111C',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 2,
            size: '818.93 MB',
            size_bytes: 858710344,
            date_uploaded: '2021-03-11 14:44:09',
            date_uploaded_unix: 1615470249,
          },
          {
            url: 'https://yts.mx/torrent/download/BC1BE1DC05D84D722EA34B499C6816D9EB681727',
            hash: 'BC1BE1DC05D84D722EA34B499C6816D9EB681727',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 2,
            size: '1.48 GB',
            size_bytes: 1589137900,
            date_uploaded: '2021-03-11 15:47:13',
            date_uploaded_unix: 1615474033,
          },
        ],
        date_uploaded: '2021-03-11 14:44:09',
        date_uploaded_unix: 1615470249,
      },
      {
        id: 21132,
        url: 'https://yts.mx/movies/the-shaolin-avengers-1976',
        imdb_code: 'tt0074513',
        title: 'The Shaolin Avengers',
        title_english: 'The Shaolin Avengers',
        title_long: 'The Shaolin Avengers (1976)',
        slug: 'the-shaolin-avengers-1976',
        year: 1976,
        rating: 6.2,
        runtime: 0,
        genres: ['Action', 'Drama'],
        summary:
          "The famous story of the Shaolin Temple's betrayal by the White-Browed Hermit, and the subsequent revenge by Shaolin firebrand Fang Shih-yu.",
        description_full:
          "The famous story of the Shaolin Temple's betrayal by the White-Browed Hermit, and the subsequent revenge by Shaolin firebrand Fang Shih-yu.",
        synopsis:
          "The famous story of the Shaolin Temple's betrayal by the White-Browed Hermit, and the subsequent revenge by Shaolin firebrand Fang Shih-yu.",
        yt_trailer_code: 'up8C87LTnfM',
        language: 'zh',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/the_shaolin_avengers_1976/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/the_shaolin_avengers_1976/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/the_shaolin_avengers_1976/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/the_shaolin_avengers_1976/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/the_shaolin_avengers_1976/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/587DCB08D806B3BC0DE3A5328DEC237D55598716',
            hash: '587DCB08D806B3BC0DE3A5328DEC237D55598716',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 1,
            size: '890.54 MB',
            size_bytes: 933798871,
            date_uploaded: '2020-09-13 13:10:48',
            date_uploaded_unix: 1599995448,
          },
          {
            url: 'https://yts.mx/torrent/download/E0AA694E54211AA59E1C52C9B8577203BA571F12',
            hash: 'E0AA694E54211AA59E1C52C9B8577203BA571F12',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 3,
            peers: 2,
            size: '1.61 GB',
            size_bytes: 1728724337,
            date_uploaded: '2020-09-13 15:08:13',
            date_uploaded_unix: 1600002493,
          },
        ],
        date_uploaded: '2020-09-13 13:10:48',
        date_uploaded_unix: 1599995448,
      },
      {
        id: 16526,
        url: 'https://yts.mx/movies/avengers-confidential-black-widow-punisher-2014',
        imdb_code: 'tt3482378',
        title: 'Avengers Confidential: Black Widow & Punisher',
        title_english: 'Avengers Confidential: Black Widow & Punisher',
        title_long: 'Avengers Confidential: Black Widow & Punisher (2014)',
        slug: 'avengers-confidential-black-widow-punisher-2014',
        year: 2014,
        rating: 5.7,
        runtime: 83,
        genres: ['Action', 'Adventure', 'Animation', 'Family', 'Sci-Fi'],
        summary:
          'After interfering with a top secret mission, THE PUNISHER is taken into custody by S.H.I.E.L.D. AGENT and AVENGER, BLACK WIDOW. At the orders of Director Nick Fury, Punisher and Black Widow are sent on a mission to stop LEVIATHAN, a global terrorist organization, that plans to sell stolen S.H.I.E.L.D. technology to the highest bidder. Now, the vigilante and spy must work together to prevent this technology from falling into the wrong hands. The fate of the world, and of the AVENGERS, hangs in the balance.—Anonymous',
        description_full:
          'After interfering with a top secret mission, THE PUNISHER is taken into custody by S.H.I.E.L.D. AGENT and AVENGER, BLACK WIDOW. At the orders of Director Nick Fury, Punisher and Black Widow are sent on a mission to stop LEVIATHAN, a global terrorist organization, that plans to sell stolen S.H.I.E.L.D. technology to the highest bidder. Now, the vigilante and spy must work together to prevent this technology from falling into the wrong hands. The fate of the world, and of the AVENGERS, hangs in the balance.—Anonymous',
        synopsis:
          'After interfering with a top secret mission, THE PUNISHER is taken into custody by S.H.I.E.L.D. AGENT and AVENGER, BLACK WIDOW. At the orders of Director Nick Fury, Punisher and Black Widow are sent on a mission to stop LEVIATHAN, a global terrorist organization, that plans to sell stolen S.H.I.E.L.D. technology to the highest bidder. Now, the vigilante and spy must work together to prevent this technology from falling into the wrong hands. The fate of the world, and of the AVENGERS, hangs in the balance.—Anonymous',
        yt_trailer_code: 's5mpaToJ6V8',
        language: 'ja',
        mpa_rating: 'PG-13',
        background_image:
          'https://yts.mx/assets/images/movies/avengers_confidential_black_widow_punisher_2014/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avengers_confidential_black_widow_punisher_2014/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avengers_confidential_black_widow_punisher_2014/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avengers_confidential_black_widow_punisher_2014/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avengers_confidential_black_widow_punisher_2014/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/C734435990BFD0614495F11B674F6291A4C48F69',
            hash: 'C734435990BFD0614495F11B674F6291A4C48F69',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 5,
            peers: 1,
            size: '759.43 MB',
            size_bytes: 796320072,
            date_uploaded: '2020-04-07 17:35:04',
            date_uploaded_unix: 1586273704,
          },
          {
            url: 'https://yts.mx/torrent/download/353D484AFC543C48721643AE9B58D52352B43A6E',
            hash: '353D484AFC543C48721643AE9B58D52352B43A6E',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '5.1',
            seeds: 7,
            peers: 0,
            size: '1.52 GB',
            size_bytes: 1632087572,
            date_uploaded: '2020-04-07 19:21:53',
            date_uploaded_unix: 1586280113,
          },
        ],
        date_uploaded: '2020-04-07 17:35:04',
        date_uploaded_unix: 1586273704,
      },
      {
        id: 13249,
        url: 'https://yts.mx/movies/avenger-dogs-2019',
        imdb_code: 'tt9724068',
        title: 'Avenger Dogs',
        title_english: 'Avenger Dogs',
        title_long: 'Avenger Dogs (2019)',
        slug: 'avenger-dogs-2019',
        year: 2019,
        rating: 2.2,
        runtime: 71,
        genres: ['Action', 'Animation'],
        summary:
          "When the universe's highest-flying dogs warp into outer space, Skyfetcher and Spaceslobber get a call from canine headquarters! It seems an unknown force is attacking unsuspecting planets, and it's up to them to root out the source of the trouble!",
        description_full:
          "When the universe's highest-flying dogs warp into outer space, Skyfetcher and Spaceslobber get a call from canine headquarters! It seems an unknown force is attacking unsuspecting planets, and it's up to them to root out the source of the trouble!",
        synopsis:
          "When the universe's highest-flying dogs warp into outer space, Skyfetcher and Spaceslobber get a call from canine headquarters! It seems an unknown force is attacking unsuspecting planets, and it's up to them to root out the source of the trouble!",
        yt_trailer_code: 'HEG4mKuhgTg',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/avenger_dogs_2019/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avenger_dogs_2019/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avenger_dogs_2019/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avenger_dogs_2019/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avenger_dogs_2019/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/EEA73729BED5FFC8924DEAA99526CD6D1E509747',
            hash: 'EEA73729BED5FFC8924DEAA99526CD6D1E509747',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 3,
            peers: 0,
            size: '612.12 MB',
            size_bytes: 641854341,
            date_uploaded: '2019-08-13 22:55:11',
            date_uploaded_unix: 1565729711,
          },
          {
            url: 'https://yts.mx/torrent/download/2524FA5CF6297836A76402771CA702A0061A9CDD',
            hash: '2524FA5CF6297836A76402771CA702A0061A9CDD',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 9,
            size: '1.14 GB',
            size_bytes: 1224065679,
            date_uploaded: '2019-08-14 00:22:40',
            date_uploaded_unix: 1565734960,
          },
        ],
        date_uploaded: '2019-08-13 22:55:11',
        date_uploaded_unix: 1565729711,
      },
      {
        id: 13106,
        url: 'https://yts.mx/movies/avengers-endgame-2019',
        imdb_code: 'tt4154796',
        title: 'Avengers: Endgame',
        title_english: 'Avengers: Endgame',
        title_long: 'Avengers: Endgame (2019)',
        slug: 'avengers-endgame-2019',
        year: 2019,
        rating: 8.4,
        runtime: 181,
        genres: ['Action', 'Adventure', 'Drama', 'Sci-Fi'],
        summary:
          'After half of all life is snapped away by Thanos, the Avengers are left scattered and divided. Now with a way to reverse the damage, the Avengers and their allies must assemble once more and learn to put differences aside in order to work together and set things right. Along the way, the Avengers realize that sacrifices must be made as they prepare for the ultimate final showdown with Thanos, which will result in the heroes fighting the biggest battle they have ever faced.—Blazer346',
        description_full:
          'After half of all life is snapped away by Thanos, the Avengers are left scattered and divided. Now with a way to reverse the damage, the Avengers and their allies must assemble once more and learn to put differences aside in order to work together and set things right. Along the way, the Avengers realize that sacrifices must be made as they prepare for the ultimate final showdown with Thanos, which will result in the heroes fighting the biggest battle they have ever faced.—Blazer346',
        synopsis:
          'After half of all life is snapped away by Thanos, the Avengers are left scattered and divided. Now with a way to reverse the damage, the Avengers and their allies must assemble once more and learn to put differences aside in order to work together and set things right. Along the way, the Avengers realize that sacrifices must be made as they prepare for the ultimate final showdown with Thanos, which will result in the heroes fighting the biggest battle they have ever faced.—Blazer346',
        yt_trailer_code: 'AMSITikqKiM',
        language: 'en',
        mpa_rating: 'PG-13',
        background_image:
          'https://yts.mx/assets/images/movies/avengers_endgame_2019/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avengers_endgame_2019/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avengers_endgame_2019/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avengers_endgame_2019/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avengers_endgame_2019/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/134F7AF967DBDB585A934A24C9F2A2EEE72E2A93',
            hash: '134F7AF967DBDB585A934A24C9F2A2EEE72E2A93',
            quality: '3D',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 32,
            peers: 2,
            size: '2.84 GB',
            size_bytes: 3049426780,
            date_uploaded: '2019-08-28 14:51:56',
            date_uploaded_unix: 1566996716,
          },
          {
            url: 'https://yts.mx/torrent/download/5A4140BD59D66BCAC57CF05AF4A8FAB4EBCAE1C1',
            hash: '5A4140BD59D66BCAC57CF05AF4A8FAB4EBCAE1C1',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 100,
            peers: 42,
            size: '1.43 GB',
            size_bytes: 1535450808,
            date_uploaded: '2019-08-01 14:19:21',
            date_uploaded_unix: 1564661961,
          },
          {
            url: 'https://yts.mx/torrent/download/223F7484D326AD8EFD3CF1E548DED524833CB77E',
            hash: '223F7484D326AD8EFD3CF1E548DED524833CB77E',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 100,
            peers: 95,
            size: '3.01 GB',
            size_bytes: 3231962890,
            date_uploaded: '2019-08-01 17:07:29',
            date_uploaded_unix: 1564672049,
          },
          {
            url: 'https://yts.mx/torrent/download/709FBD48374D2AE13C11B07A26B5E7DDC727D720',
            hash: '709FBD48374D2AE13C11B07A26B5E7DDC727D720',
            quality: '2160p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x265',
            bit_depth: '10',
            audio_channels: '5.1',
            seeds: 100,
            peers: 51,
            size: '5.26 GB',
            size_bytes: 5647881994,
            date_uploaded: '2020-02-09 02:11:11',
            date_uploaded_unix: 1581210671,
          },
          {
            url: 'https://yts.mx/torrent/download/9D62160EEE330397A7A7BABA989A269C58CCFD8E',
            hash: '9D62160EEE330397A7A7BABA989A269C58CCFD8E',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 50,
            peers: 2,
            size: '1.43 GB',
            size_bytes: 1535450808,
            date_uploaded: '2019-07-29 18:45:19',
            date_uploaded_unix: 1564418719,
          },
          {
            url: 'https://yts.mx/torrent/download/414A6F933C48FC7543A9CDB42C854B5457C5BCC7',
            hash: '414A6F933C48FC7543A9CDB42C854B5457C5BCC7',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 100,
            peers: 16,
            size: '3 GB',
            size_bytes: 3221225472,
            date_uploaded: '2019-07-29 21:31:21',
            date_uploaded_unix: 1564428681,
          },
        ],
        date_uploaded: '2019-07-29 18:45:19',
        date_uploaded_unix: 1564418719,
      },
      {
        id: 11620,
        url: 'https://yts.mx/movies/ultimate-avengers-ii-2006',
        imdb_code: 'tt0803093',
        title: 'Ultimate Avengers II',
        title_english: 'Ultimate Avengers II',
        title_long: 'Ultimate Avengers II (2006)',
        slug: 'ultimate-avengers-ii-2006',
        year: 2006,
        rating: 6.5,
        runtime: 73,
        genres: ['Action', 'Adventure', 'Animation', 'Sci-Fi'],
        summary:
          "The mightiest of heroes the ultimate Avengers must continue their war against the same aliens they fought. This time, the aliens and Captain America's old enemy Herr Kleiser (the alien shape shifter who supposedly died in 1945), are invading a hidden city in Africa, where the Black Panther is king. But when Kleiser murders the Black Panther's father T'Chaka, Black Panther travels to the U.S.A. to get advice from Captain America. The Avengers must travel to Africa, where a bloody war will be waged against the invading aliens.—Anthony Pereyra {hypersonic91@yahoo.com}",
        description_full:
          "The mightiest of heroes the ultimate Avengers must continue their war against the same aliens they fought. This time, the aliens and Captain America's old enemy Herr Kleiser (the alien shape shifter who supposedly died in 1945), are invading a hidden city in Africa, where the Black Panther is king. But when Kleiser murders the Black Panther's father T'Chaka, Black Panther travels to the U.S.A. to get advice from Captain America. The Avengers must travel to Africa, where a bloody war will be waged against the invading aliens.—Anthony Pereyra {hypersonic91@yahoo.com}",
        synopsis:
          "The mightiest of heroes the ultimate Avengers must continue their war against the same aliens they fought. This time, the aliens and Captain America's old enemy Herr Kleiser (the alien shape shifter who supposedly died in 1945), are invading a hidden city in Africa, where the Black Panther is king. But when Kleiser murders the Black Panther's father T'Chaka, Black Panther travels to the U.S.A. to get advice from Captain America. The Avengers must travel to Africa, where a bloody war will be waged against the invading aliens.—Anthony Pereyra {hypersonic91@yahoo.com}",
        yt_trailer_code: 'gl4jsZcYt9k',
        language: 'en',
        mpa_rating: 'PG-13',
        background_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_ii_2006/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/ultimate_avengers_ii_2006/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_ii_2006/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_ii_2006/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_ii_2006/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/60037FB21F9872B2EAD6E506B1F10B0CAB8FFC50',
            hash: '60037FB21F9872B2EAD6E506B1F10B0CAB8FFC50',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 7,
            peers: 1,
            size: '630.39 MB',
            size_bytes: 661011825,
            date_uploaded: '2019-04-18 23:21:06',
            date_uploaded_unix: 1555622466,
          },
          {
            url: 'https://yts.mx/torrent/download/6918AF54D13A05E41D8BAFA311A8CA6126866929',
            hash: '6918AF54D13A05E41D8BAFA311A8CA6126866929',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 13,
            peers: 1,
            size: '1.17 GB',
            size_bytes: 1256277934,
            date_uploaded: '2019-04-19 00:35:27',
            date_uploaded_unix: 1555626927,
          },
        ],
        date_uploaded: '2019-04-18 23:21:06',
        date_uploaded_unix: 1555622466,
      },
      {
        id: 11609,
        url: 'https://yts.mx/movies/ultimate-avengers-the-movie-2006',
        imdb_code: 'tt0491703',
        title: 'Ultimate Avengers: The Movie',
        title_english: 'Ultimate Avengers: The Movie',
        title_long: 'Ultimate Avengers: The Movie (2006)',
        slug: 'ultimate-avengers-the-movie-2006',
        year: 2006,
        rating: 6.6,
        runtime: 72,
        genres: ['Action', 'Adventure', 'Animation', 'Sci-Fi'],
        summary:
          "In 1945, Captain America, U.S. soldier created with a Super-Soldier Serum, is fighting the Nazis during World War II, and after averting a nuclear disaster, he falls into the icy waters of the North Atlantic, and frozen in suspended animation, only to be revived in the twenty-first century by the American military, who are hoping that they can recreate the serum in Captain America's blood in order to create more super-soldiers. But now, with the world facing the very same evil, Captain America must rise again as our last hope of survival, and lead a strong-willed team of today's superheroes.—Anthony Pereyra {hypersonic91@yahoo.com}",
        description_full:
          "In 1945, Captain America, U.S. soldier created with a Super-Soldier Serum, is fighting the Nazis during World War II, and after averting a nuclear disaster, he falls into the icy waters of the North Atlantic, and frozen in suspended animation, only to be revived in the twenty-first century by the American military, who are hoping that they can recreate the serum in Captain America's blood in order to create more super-soldiers. But now, with the world facing the very same evil, Captain America must rise again as our last hope of survival, and lead a strong-willed team of today's superheroes.—Anthony Pereyra {hypersonic91@yahoo.com}",
        synopsis:
          "In 1945, Captain America, U.S. soldier created with a Super-Soldier Serum, is fighting the Nazis during World War II, and after averting a nuclear disaster, he falls into the icy waters of the North Atlantic, and frozen in suspended animation, only to be revived in the twenty-first century by the American military, who are hoping that they can recreate the serum in Captain America's blood in order to create more super-soldiers. But now, with the world facing the very same evil, Captain America must rise again as our last hope of survival, and lead a strong-willed team of today's superheroes.—Anthony Pereyra {hypersonic91@yahoo.com}",
        yt_trailer_code: 'IQ9QjHVaurM',
        language: 'en',
        mpa_rating: 'PG-13',
        background_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_2006/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/ultimate_avengers_2006/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_2006/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_2006/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/ultimate_avengers_2006/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/E1D487EE85337121563B0038FFA8CCDE71D30D8F',
            hash: 'E1D487EE85337121563B0038FFA8CCDE71D30D8F',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 6,
            peers: 0,
            size: '613.76 MB',
            size_bytes: 643574006,
            date_uploaded: '2019-04-18 00:07:10',
            date_uploaded_unix: 1555538830,
          },
          {
            url: 'https://yts.mx/torrent/download/9D98222D32ADE91116856B9053E166FE11EAC8AB',
            hash: '9D98222D32ADE91116856B9053E166FE11EAC8AB',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 7,
            peers: 1,
            size: '1.15 GB',
            size_bytes: 1234803098,
            date_uploaded: '2019-04-18 01:16:00',
            date_uploaded_unix: 1555542960,
          },
        ],
        date_uploaded: '2019-04-18 00:07:10',
        date_uploaded_unix: 1555538830,
      },
      {
        id: 7966,
        url: 'https://yts.mx/movies/the-toxic-avenger-the-musical-2018',
        imdb_code: 'tt8083622',
        title: 'The Toxic Avenger: The Musical',
        title_english: 'The Toxic Avenger: The Musical',
        title_long: 'The Toxic Avenger: The Musical (2018)',
        slug: 'the-toxic-avenger-the-musical-2018',
        year: 2018,
        rating: 6.4,
        runtime: 121,
        genres: ['Action', 'Musical'],
        summary:
          'A musical adaptation of the 1984 movie by the same name. "A movie that most people only watched while stoned." A dystopian future of global warming and ecological disaster. While trying to get to the bottom of who\'s dumping the toxic waste in New Jersey, his discovery leads him to being dumped in the toxic waste to die only to come out as a super strong mutant.—gambitx-00042',
        description_full:
          'A musical adaptation of the 1984 movie by the same name. "A movie that most people only watched while stoned." A dystopian future of global warming and ecological disaster. While trying to get to the bottom of who\'s dumping the toxic waste in New Jersey, his discovery leads him to being dumped in the toxic waste to die only to come out as a super strong mutant.—gambitx-00042',
        synopsis:
          'A musical adaptation of the 1984 movie by the same name. "A movie that most people only watched while stoned." A dystopian future of global warming and ecological disaster. While trying to get to the bottom of who\'s dumping the toxic waste in New Jersey, his discovery leads him to being dumped in the toxic waste to die only to come out as a super strong mutant.—gambitx-00042',
        yt_trailer_code: 'CgL0o7nGk1M',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/the_toxic_avenger_the_musical_2018/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/the_toxic_avenger_the_musical_2018/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/the_toxic_avenger_the_musical_2018/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/the_toxic_avenger_the_musical_2018/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/the_toxic_avenger_the_musical_2018/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/A3A9C40351682F8918B6C81E287740815B9BC25A',
            hash: 'A3A9C40351682F8918B6C81E287740815B9BC25A',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 1,
            peers: 2,
            size: '1.01 GB',
            size_bytes: 1084479242,
            date_uploaded: '2018-06-08 05:37:04',
            date_uploaded_unix: 1528429024,
          },
          {
            url: 'https://yts.mx/torrent/download/B05F45E0958CA831BFFC1C40D65C261286F3D7E7',
            hash: 'B05F45E0958CA831BFFC1C40D65C261286F3D7E7',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 6,
            peers: 2,
            size: '1.94 GB',
            size_bytes: 2083059139,
            date_uploaded: '2018-06-08 08:07:39',
            date_uploaded_unix: 1528438059,
          },
        ],
        date_uploaded: '2018-06-08 05:37:04',
        date_uploaded_unix: 1528429024,
      },
      {
        id: 7722,
        url: 'https://yts.mx/movies/avengers-grimm-time-wars-2018',
        imdb_code: 'tt8159584',
        title: 'Avengers Grimm: Time Wars',
        title_english: 'Avengers Grimm: Time Wars',
        title_long: 'Avengers Grimm: Time Wars (2018)',
        slug: 'avengers-grimm-time-wars-2018',
        year: 2018,
        rating: 2.5,
        runtime: 88,
        genres: ['Action', 'Adventure', 'Fantasy'],
        summary:
          'When Rumpelstiltskin tries to take over Earth once and for all, The Avengers Grimm must track him down through time in order to defeat him.',
        description_full:
          'When Rumpelstiltskin tries to take over Earth once and for all, The Avengers Grimm must track him down through time in order to defeat him.',
        synopsis:
          'When Rumpelstiltskin tries to take over Earth once and for all, The Avengers Grimm must track him down through time in order to defeat him.',
        yt_trailer_code: 'm9fvrfoVJDs',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/avengers_grimm_time_wars_2018/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avengers_grimm_time_wars_2018/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avengers_grimm_time_wars_2018/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avengers_grimm_time_wars_2018/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avengers_grimm_time_wars_2018/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/4AA94D343229166E9808FCEE3CD1F97F6181D378',
            hash: '4AA94D343229166E9808FCEE3CD1F97F6181D378',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 0,
            size: '747.14 MB',
            size_bytes: 783433073,
            date_uploaded: '2018-07-17 11:40:55',
            date_uploaded_unix: 1531820455,
          },
          {
            url: 'https://yts.mx/torrent/download/3AB883C86273E01909A899BC5C32FAB19D8ECF9E',
            hash: '3AB883C86273E01909A899BC5C32FAB19D8ECF9E',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 4,
            peers: 5,
            size: '1.4 GB',
            size_bytes: 1503238554,
            date_uploaded: '2018-07-17 13:38:30',
            date_uploaded_unix: 1531827510,
          },
          {
            url: 'https://yts.mx/torrent/download/9242AE0794C0AE595BCCE0EED3005B5B7968C60F',
            hash: '9242AE0794C0AE595BCCE0EED3005B5B7968C60F',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 0,
            peers: 0,
            size: '748 MB',
            size_bytes: 784334848,
            date_uploaded: '2018-05-03 17:43:57',
            date_uploaded_unix: 1525362237,
          },
          {
            url: 'https://yts.mx/torrent/download/14B7B937A087FF46B2A8E64DA2FD94A8A7B572B8',
            hash: '14B7B937A087FF46B2A8E64DA2FD94A8A7B572B8',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 0,
            size: '1.4 GB',
            size_bytes: 1503238554,
            date_uploaded: '2018-05-03 19:20:58',
            date_uploaded_unix: 1525368058,
          },
        ],
        date_uploaded: '2018-05-03 17:43:57',
        date_uploaded_unix: 1525362237,
      },
      {
        id: 7424,
        url: 'https://yts.mx/movies/avenger-2006',
        imdb_code: 'tt0473445',
        title: 'Avenger',
        title_english: 'Avenger',
        title_long: 'Avenger (2006)',
        slug: 'avenger-2006',
        year: 2006,
        rating: 5.6,
        runtime: 92,
        genres: ['Action', 'Thriller'],
        summary:
          'After his own daughter was killed in Panama in 1994, former C.I.A. Agent Calvin Dexter became a private "specialist" in cases which wouldn\'t reach justice trough the regular legal channels. Two years later, he accepts to find Richard "Rickie" Edmonds for his pa, influential rich businessman Stephen Edmonds. Rickie left for a private Canadian war victims charity in Bosnia and went missing. Dexter discovers Rickie was beaten to a pulp and drowned for no other crime then helping street boys from the other side by Zoran Zilic and his Serbian paramilitary "order". He offers Stephen to "finish the job", as such war criminals don\'t go to trial. But Deputy C.I.A. Director Paul Devereaux cares only for a nuclear arms project, for which he wants to use Zilic. So C.I.A. troubleshooter Frank McBride is ordered to protect him and handle Dexter.—KGF Vissers',
        description_full:
          'After his own daughter was killed in Panama in 1994, former C.I.A. Agent Calvin Dexter became a private "specialist" in cases which wouldn\'t reach justice trough the regular legal channels. Two years later, he accepts to find Richard "Rickie" Edmonds for his pa, influential rich businessman Stephen Edmonds. Rickie left for a private Canadian war victims charity in Bosnia and went missing. Dexter discovers Rickie was beaten to a pulp and drowned for no other crime then helping street boys from the other side by Zoran Zilic and his Serbian paramilitary "order". He offers Stephen to "finish the job", as such war criminals don\'t go to trial. But Deputy C.I.A. Director Paul Devereaux cares only for a nuclear arms project, for which he wants to use Zilic. So C.I.A. troubleshooter Frank McBride is ordered to protect him and handle Dexter.—KGF Vissers',
        synopsis:
          'After his own daughter was killed in Panama in 1994, former C.I.A. Agent Calvin Dexter became a private "specialist" in cases which wouldn\'t reach justice trough the regular legal channels. Two years later, he accepts to find Richard "Rickie" Edmonds for his pa, influential rich businessman Stephen Edmonds. Rickie left for a private Canadian war victims charity in Bosnia and went missing. Dexter discovers Rickie was beaten to a pulp and drowned for no other crime then helping street boys from the other side by Zoran Zilic and his Serbian paramilitary "order". He offers Stephen to "finish the job", as such war criminals don\'t go to trial. But Deputy C.I.A. Director Paul Devereaux cares only for a nuclear arms project, for which he wants to use Zilic. So C.I.A. troubleshooter Frank McBride is ordered to protect him and handle Dexter.—KGF Vissers',
        yt_trailer_code: 'HUmHYwVCuhg',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/avenger_2006/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avenger_2006/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avenger_2006/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avenger_2006/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avenger_2006/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/E37DDBCE501C911F439FAEF93D1DEEA9A986C2A9',
            hash: 'E37DDBCE501C911F439FAEF93D1DEEA9A986C2A9',
            quality: '720p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 1,
            size: '761.09 MB',
            size_bytes: 798060708,
            date_uploaded: '2018-03-28 04:02:12',
            date_uploaded_unix: 1522202532,
          },
          {
            url: 'https://yts.mx/torrent/download/39886A023D1B478177739DE4D45CC30305C26986',
            hash: '39886A023D1B478177739DE4D45CC30305C26986',
            quality: '1080p',
            type: 'web',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 5,
            peers: 0,
            size: '1.44 GB',
            size_bytes: 1546188227,
            date_uploaded: '2018-03-28 08:20:48',
            date_uploaded_unix: 1522218048,
          },
        ],
        date_uploaded: '2018-03-28 04:02:12',
        date_uploaded_unix: 1522202532,
      },
      {
        id: 4522,
        url: 'https://yts.mx/movies/avengers-age-of-ultron-2015',
        imdb_code: 'tt2395427',
        title: 'Avengers: Age of Ultron',
        title_english: 'Avengers: Age of Ultron',
        title_long: 'Avengers: Age of Ultron (2015)',
        slug: 'avengers-age-of-ultron-2015',
        year: 2015,
        rating: 7.3,
        runtime: 141,
        genres: ['Action', 'Adventure', 'Sci-Fi'],
        summary:
          "The Avengers raid a Hydra base in Sokovia commanded by Strucker and they retrieve Loki's scepter. They also discover that Strucker had been conducting experiments with the orphan twins Pietro Maximoff, who has super speed, and Wanda Maximoff, who can control minds and project energy. Tony Stark discovers an Artificial Intelligence in the scepter and convinces Bruce Banner to secretly help him to transfer the A.I. to his Ultron defense system. However, the Ultron decides that is necessary to annihilate mankind in order to save the planet, attacks the Avengers and flees to Sokovia with the scepter. He builds an armature for self-protection and robots for his army and teams up with the twins. The Avengers go to Clinton Barton's house to recover, but out of the blue, Nick Fury arrives and convinces them to fight against Ultron. Will they succeed?—Claudio Carvalho, Rio de Janeiro, Brazil",
        description_full:
          "The Avengers raid a Hydra base in Sokovia commanded by Strucker and they retrieve Loki's scepter. They also discover that Strucker had been conducting experiments with the orphan twins Pietro Maximoff, who has super speed, and Wanda Maximoff, who can control minds and project energy. Tony Stark discovers an Artificial Intelligence in the scepter and convinces Bruce Banner to secretly help him to transfer the A.I. to his Ultron defense system. However, the Ultron decides that is necessary to annihilate mankind in order to save the planet, attacks the Avengers and flees to Sokovia with the scepter. He builds an armature for self-protection and robots for his army and teams up with the twins. The Avengers go to Clinton Barton's house to recover, but out of the blue, Nick Fury arrives and convinces them to fight against Ultron. Will they succeed?—Claudio Carvalho, Rio de Janeiro, Brazil",
        synopsis:
          "The Avengers raid a Hydra base in Sokovia commanded by Strucker and they retrieve Loki's scepter. They also discover that Strucker had been conducting experiments with the orphan twins Pietro Maximoff, who has super speed, and Wanda Maximoff, who can control minds and project energy. Tony Stark discovers an Artificial Intelligence in the scepter and convinces Bruce Banner to secretly help him to transfer the A.I. to his Ultron defense system. However, the Ultron decides that is necessary to annihilate mankind in order to save the planet, attacks the Avengers and flees to Sokovia with the scepter. He builds an armature for self-protection and robots for his army and teams up with the twins. The Avengers go to Clinton Barton's house to recover, but out of the blue, Nick Fury arrives and convinces them to fight against Ultron. Will they succeed?—Claudio Carvalho, Rio de Janeiro, Brazil",
        yt_trailer_code: 'JAUoeqvedMo',
        language: 'en',
        mpa_rating: 'PG-13',
        background_image:
          'https://yts.mx/assets/images/movies/avengers_age_of_ultron_2015/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/avengers_age_of_ultron_2015/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/avengers_age_of_ultron_2015/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/avengers_age_of_ultron_2015/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/avengers_age_of_ultron_2015/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/A5321DCF074AC864C4728D8B9307986302A7592C',
            hash: 'A5321DCF074AC864C4728D8B9307986302A7592C',
            quality: '3D',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 2,
            peers: 0,
            size: '2.05 GB',
            size_bytes: 2201170739,
            date_uploaded: '2015-11-12 18:05:58',
            date_uploaded_unix: 1447347958,
          },
          {
            url: 'https://yts.mx/torrent/download/F2A0F56A420906CC8B539C6AEB454992242A6712',
            hash: 'F2A0F56A420906CC8B539C6AEB454992242A6712',
            quality: '720p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 39,
            peers: 14,
            size: '931.01 MB',
            size_bytes: 976234742,
            date_uploaded: '2015-11-12 18:05:58',
            date_uploaded_unix: 1447347958,
          },
          {
            url: 'https://yts.mx/torrent/download/92B4D5EA2D21BC2692A2CB1E5B9FBECD489863EC',
            hash: '92B4D5EA2D21BC2692A2CB1E5B9FBECD489863EC',
            quality: '1080p',
            type: 'bluray',
            is_repack: '0',
            video_codec: 'x264',
            bit_depth: '8',
            audio_channels: '2.0',
            seeds: 100,
            peers: 100,
            size: '2.05 GB',
            size_bytes: 2201170739,
            date_uploaded: '2015-11-12 18:05:58',
            date_uploaded_unix: 1447347958,
          },
          {
            url: 'https://yts.mx/torrent/download/528E5AF5BC4924B1261E6B354B974DF1728E6F60',
            hash: '528E5AF5BC4924B1261E6B354B974DF1728E6F60',
            quality: '2160p',
            type: 'bluray',
            is_repack: '',
            video_codec: 'x265',
            bit_depth: '10',
            audio_channels: '5.1',
            seeds: 67,
            peers: 18,
            size: '6.49 GB',
            size_bytes: 6968584438,
            date_uploaded: '2022-04-12 15:25:01',
            date_uploaded_unix: 1649769901,
          },
        ],
        date_uploaded: '2015-11-12 18:05:58',
        date_uploaded_unix: 1447347958,
      },
    ],
  },
};
